import type AudioMotionOptions from "audiomotion-analyzer";

export const createAudioMotionConfig = (
	audio: HTMLAudioElement,
	width: number,
	height: number,
) => ({
	source: audio,
	height,
	width,
	alphaBars: false,
	ansiBands: true,
	barSpace: 0.25,
	bgAlpha: 0,
	channelLayout: "single",
	colorMode: "gradient",
	fftSize: 8192,
	fillAlpha: 0.6,
	frequencyScale: "log",
	gradient: "rainbow",
	ledBars: false,
	linearAmplitude: true,
	linearBoost: 1.8,
	lineWidth: 1.5,
	loRes: false,
	lumiBars: false,
	maxDecibels: -25,
	maxFPS: 0,
	maxFreq: 20000,
	minDecibels: -85,
	minFreq: 20,
	mirror: 1,
	mode: 2,
	noteLabels: false,
	outlineBars: false,
	overlay: true,
	peakLine: false,
	radial: false,
	radialInvert: false,
	radius: 0.3,
	reflexAlpha: 0.25,
	reflexFit: true,
	reflexRatio: 0.3,
	roundBars: false,
	showBgColor: true,
	showFPS: false,
	showPeaks: true,
	showScaleX: false,
	showScaleY: false,
	smoothing: 0.5,
	spinSpeed: 1,
	splitGradient: false,
	trueLeds: true,
	useCanvas: true,
	volume: 1,
	weightingFilter: "D",
});
